layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    - yutayamate

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: yuta.yamate
  # hackerrank: your_username
  instagram: yuta.yamate
  # keybase: your_username
  linkedin: yuta-yamate
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: yutayamate
  # unsplash: your_username
  # vk: your_username
  website: https://www.yutayamate.com
  # youtube: your_username

topics:
  - name: Application security
    web_url: https://github.com/topics/application-security

  - name: Penetration testing
    web_url: https://github.com/topics/penetration-testing

  - name: Digital forensics
    web_url: https://github.com/topics/forensics

  - name: Data visualization
    web_url: https://github.com/topics/data-visualization

  - name: OWASP
    web_url: https://github.com/topics/owasp
    image_url: https://avatars.githubusercontent.com/u/155815

  - name: HackTheBox
    web_url: https://github.com/topics/hackthebox
    image_url: https://avatars.githubusercontent.com/u/31746234

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png

  - name: Jenkins
    web_url: https://github.com/topics/jenkins
    image_url: https://raw.githubusercontent.com/github/explore/4546263bd5739353083c33dada43f8f31e7d1fd6/topics/jenkins/jenkins.png

  - name: macOS
    web_url: https://github.com/topics/macos
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/macos/macos.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png

  - name: Visual Studio Code
    web_url: https://github.com/topics/vscode
    image_url: https://raw.githubusercontent.com/github/explore/bbd48b997e8d0bef63f676eca4da5e1f76487b56/topics/visual-studio-code/visual-studio-code.png
